export interface ParticipantData {
  "#": number | null;
  "Apellido paterno": string | null;
  "Apellido materno": string | null;
  "Nombre": string | null;
  "Prueba": string | null;
  "# Empleado": string | null;
  "Edad": number | null;
  "Genero": string | null;
  "Categoria": string | null;
  "Altura [cm]": number | null;
  "Peso [kg]": number | null;
  "Grasa [%]": number | null;
  "IMC": number | null;
  "Cintura [cm]": number | null;
  "BMI": number | null;
  "BMR": number | null;
  "Fatmass": number | null;
  "FFM": number | null;
  "TBW": number | null;
  "Agarre": number | null;
  "Puntos": number | null;
  "Salto": number | null;
  "Puntos_1": number | null;
  "Agilidad": number | null;
  "Puntos_2": number | null;
  "Resistencia": string | null;
  "Puntos_3": number | null;
  "Total": number | null;
}